[package]
name = "rect_shape_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#We need to declare as proc macro
[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
